# login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "newuser1@gmail.com",
  "password": "password123"
}

###

# signup
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### 

# Get a user
GET http://localhost:4000/api/user
Content-Type: application/json
Authorization: Bearer 


###

# Get top-rated movies
GET http://localhost:4000/api/movies/top-rated
Content-Type: application/json

###
# Get movie details
GET http://localhost:4000/api/movies/movie/19995
Content-Type: application/json

###
# Search for movies
GET http://localhost:4000/api/movies/search?q=Avatar
Content-Type: application/json

###
# Add a movie to the interested list
POST http://localhost:4000/api/user/681cc36b0cb3dca7e6b3b924/interested
Content-Type: application/json
Authorization: Bearer 

{
  "movieId": "",
  "title": "Thunderbolts",
  "comment": "Excited to watch this cool movie!"
}

###
# Add a movie to the seen list (and remove from interested)
POST http://localhost:4000/api/user/681cc36b0cb3dca7e6b3b924/seen
Content-Type: application/json
Authorization: Bearer 

{
  "movieId": "19995",
  "title": "Avatar",
  "rating": 9,
  "comment": "Amazing visuals and story!"
}

###
# Remove a movie from the interested list
DELETE http://localhost:4000/api/user/681cc36b0cb3dca7e6b3b924/interested
Content-Type: application/json
Authorization: Bearer 

{
  "movieId": "986056"
}

###
# Remove a movie from the seen list
DELETE http://localhost:4000/api/user/681cc36b0cb3dca7e6b3b924/seen
Content-Type: application/json
Authorization: Bearer 

{
  "movieId": "19995"
}





